### ISSUE TITLE
The site is a bit heavy 

### ISSUE THREAD

**Issue by mohamadelhinamy** [El-Etreby/Scriptaholic#39]
Severity:Low
Reported By: Mohammad Amr Elhinamy
Description: When loading the home page of the website it takes some time and the video is lagging and the profile pictures of the companies shows a broken link.
Steps to reproduce the issue: 1-Load the website
                                                 2- scroll to see the video and the comapnies
                                                 3- notice the lagging of the video and the broken links of the picture.
![screenshot from 2017-05-01 14-57-52](https://cloud.githubusercontent.com/assets/25357727/25580155/a08722f2-2e7e-11e7-9ffb-602d9b64e96d.png)

the expected result : the speed of the loading can be a bit faster without lagging of the video and no broken links of the profile pictures.

**Comment by hazemsalah** [comment]
Problem with deployment and fixed
