### ISSUE TITLE
The search results are confusing 

### ISSUE THREAD

**Issue by mohamadelhinamy** [El-Etreby/Scriptaholic#40]
Severity : medium
Reported By: Mohamad Amr Elhinamy
Description: When i write anything in the search box it returns all the companies on the website even if i write a name of a compan that doesnot exist or that exists it returns all the companies on the website which is a bit confusing.
Steps to reproduce the issue: 1-open the website
                                                2-write anything in the search bar
                                                3- it will redirect you to the bottom of the homepage which contains all the companies on the website even if they are not related to your search 
![screenshot from 2017-05-01 15-12-55](https://cloud.githubusercontent.com/assets/25357727/25580395/f269715e-2e80-11e7-9a57-638cbb935c9a.png)
![screenshot from 2017-05-01 15-14-28](https://cloud.githubusercontent.com/assets/25357727/25580396/f26b4088-2e80-11e7-84df-7375b49e12b5.png)
Expected Result : it should redirect me to a page of results related to my search and if i searched for an none existing item it should notify me.

**Comment by hazemsalah** [comment]
Fixed
