### ISSUE TITLE
Website not user-friendly 

### ISSUE THREAD

**Issue by karimkozman** [El-Etreby/Scriptaholic#44]
1- Severity --> Low

2- Reported by --> Karim Kozman

3- The website is neither self-explanatory nor does it have any description on what it actually does

4- Steps to Produce The Issue:
a. open the website
b. search for any explanation/description to know what kind of site is it

5- Expected Result --> when entering the website I should see any explanation at the home page as to know what does this site do exactly

**Comment by hazemsalah** [comment]
The title of the website says it all , i dont think that iGo fits as a title for any of the 2 themes other than entertainment , we made sure to include a video that describes what the theme is , and  under the video you will find the businesses that are listed as  entertainment  businesses , we made sure to design the home page to be as clear and user friendly as possible ,but  i dont think it is logical to include a description in the home page
