### ISSUE TITLE
Rating a Company profile error

### ISSUE THREAD

**Issue by ahmedhafez1234** [El-Etreby/Scriptaholic#47]
Severity: Medium
Reported by: Ahmed Hafez
Description: You simply cannot use the rate company feature. 
Steps to reproduce the error:
- Logon into the home page search for a Company
- Click on the company name to redirect to the company's profile 
- At the bottom of the page there are rating stars click on any of them.

Expected result: An addition by 1 to the bars next to the number you've clicked on.

**Comment by hazemsalah** [comment]
the stars ar to show the average rating to rate & review you need to press on rate & review button
