### ISSUE TITLE
Search Engine not Working for any input entered by user 

### ISSUE THREAD

**Issue by OmarSwidan** [El-Etreby/Scriptaholic#48]
1- Severity --> Medium

2- Reported by --> Omar Swidan

3- when user enter a search item in the search engine box and click on search button, no result is showed for the user or any response in the website.

4- Steps to Produce The Issue:
            a. open the website
            b. enter search item in the search engine box
            c. click on the 'search' button
            d. no response from the website 

5- Expected Result --> on clicking 'Search' button, the website should show all the available results (companies, areas, cities,...) that meets the entered search item

**Comment by hazemsalah** [comment]
Fixed
