### ISSUE TITLE
Application Error ( Application error An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.)

### ISSUE THREAD

**Issue by OmarSwidan** [El-Etreby/Scriptaholic#52]
1- Severity --> High

2- Reported by --> Omar Swidan

3- suddenly, a crash happened to the application when I clicked on the Home Page 

4- Steps to Produce The Issue:
Suddenly happened without any steps and this message showed in an error page " Application error An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

5- Expected Result -->

**Comment by hazemsalah** [comment]
It was a problem woth deployment and fixed
